### ISSUE TITLE
Backwards compatibility with Android 2.3

### ISSUE THREAD

**Issue by vladgolubev** [vladgolubev/MODULE.OK#27]

**Comment by Filutkie** [comment]
Meh... Is that still required in 2015? 
minSdkVersion="14" FTW.

**Comment by samosfator** [comment]
@Filutkie Why are you so ridiculous? It took me 20 min to do this and will bring a bunch of potential users.

**Comment by samosfator** [comment]
Not works with Android 2.3 again. To investigate.
